name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg gpgsm libgpgme-dev php-cli php-dev autoconf libtool make gcc

      - name: Checkout php-gnupg
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and install php-gnupg
        run: |
          phpize
          ./configure
          make
          sudo make install

      - name: Run tests
        run: |
          make test
